import sys, os, ctypes; from PyQt6.QtCore import QUrl, Qt; from PyQt6.QtWidgets import QApplication, QMainWindow, QToolBar, QLineEdit, QVBoxLayout, QWidget, QLabel, QHBoxLayout, QPushButton; from PyQt6.QtGui import QPixmap, QImage, QIcon; from PyQt6.QtWebEngineWidgets import QWebEngineView; from PyQt6.QtWebEngineCore import QWebEngineProfile, QWebEnginePage, QWebEngineSettings;
try: ctypes.windll.shell32.SetCurrentProcessExplicitAppUserModelID("zero.browser.v1")
except: pass
app = QApplication(sys.argv); ic_p = os.path.abspath(os.path.join(os.path.dirname(__file__), "zero_icon.ico")); icon = QIcon(ic_p) if os.path.exists(ic_p) else QIcon(); app.setWindowIcon(icon); win = QMainWindow(); win.setWindowTitle("Zero Browser"); win.resize(1200, 800); win.setWindowIcon(icon);
try:
    if os.path.exists(ic_p):
        h = int(win.winId()); ctypes.windll.user32.SendMessageW(h, 0x80, 1, icon.pixmap(32, 32).handle()); ctypes.windll.user32.SendMessageW(h, 0x80, 0, icon.pixmap(16, 16).handle())
except: pass
prof = QWebEngineProfile("ZeroProfile", win); prof.setPersistentStoragePath(os.path.join(os.path.dirname(__file__), "zero_profile_data")); prof.setPersistentCookiesPolicy(QWebEngineProfile.PersistentCookiesPolicy.AllowPersistentCookies); page = QWebEnginePage(prof, win); view = QWebEngineView(); view.setPage(page); view.settings().setAttribute(QWebEngineSettings.WebAttribute.JavascriptEnabled, True); view.settings().setAttribute(QWebEngineSettings.WebAttribute.LocalStorageEnabled, True); lay = QVBoxLayout(); lay.setContentsMargins(0, 0, 0, 0); lay.setSpacing(0); tb = QToolBar(); tb.setMovable(False); tb.setStyleSheet("background:#1e1e1e;padding:5px;border:none;"); btn_s = "color:white;font-size:16px;margin-right:12px;background:none;border:none;font-weight:bold;"; b_b = QPushButton("🡨"); b_b.setStyleSheet(btn_s); b_b.clicked.connect(view.back); tb.addWidget(b_b); f_b = QPushButton("🡪"); f_b.setStyleSheet(btn_s); f_b.clicked.connect(view.forward); tb.addWidget(f_b); r_b = QPushButton("⟳"); r_b.setStyleSheet(btn_s); r_b.clicked.connect(view.reload); tb.addWidget(r_b); h_b = QPushButton("⌂"); h_b.setStyleSheet(btn_s); tb.addWidget(h_b); bar = QLineEdit(); bar.setPlaceholderText("Введите адрес сайта..."); bar.setStyleSheet("background:#121212;color:white;border:1px solid #333;border-radius:15px;padding:6px 15px;"); tb.addWidget(bar); home = QWidget(); home.setStyleSheet("background:#121212;"); h_lay = QVBoxLayout(); h_lay.setContentsMargins(0, 50, 0, 0); h_lay.setAlignment(Qt.AlignmentFlag.AlignHCenter | Qt.AlignmentFlag.AlignTop); lbl = QLabel(); lp = os.path.join(os.path.dirname(__file__), "zero_logo.png");
if os.path.exists(lp):
    img = QImage(lp).convertToFormat(QImage.Format.Format_ARGB32)
    for y in range(img.height()):
        for x in range(img.width()):
            c = img.pixelColor(x, y);
            if c.red() < 25 and c.green() < 25 and c.blue() < 25: img.setPixelColor(x, y, Qt.GlobalColor.transparent)
    px = QPixmap.fromImage(img); lbl.setPixmap(px.scaledToWidth(500, Qt.TransformationMode.SmoothTransformation))
else: lbl.setText("Zero Browser"); lbl.setStyleSheet("color:#5167fc;font-size:56px;font-weight:bold;")
lbl.setAlignment(Qt.AlignmentFlag.AlignCenter); h_lay.addWidget(lbl); h_lay.addSpacing(25); inp = QLineEdit(); inp.setPlaceholderText("Введите адрес страницы"); inp.setFixedWidth(550); inp.setStyleSheet("background:#1e1e1e;color:white;border:2px solid #2a2a2a;border-radius:25px;padding:12px 20px;font-size:16px;"); h_lay.addWidget(inp, alignment=Qt.AlignmentFlag.AlignCenter); h_lay.addStretch(1); open_u = lambda u: (home.hide(), view.show(), view.setUrl(QUrl(u if u.startswith("http") else "https://" + u))) if u.strip() else None; inp.returnPressed.connect(lambda: open_u(inp.text())); bar.returnPressed.connect(lambda: open_u(bar.text())); h_b.clicked.connect(lambda: (view.hide(), home.show(), bar.setText(""), inp.setText(""), inp.setFocus())); home.setLayout(h_lay); lay.addWidget(tb); lay.addWidget(home); lay.addWidget(view); view.hide(); cnt = QWidget(); cnt.setLayout(lay); win.setCentralWidget(cnt); view.urlChanged.connect(lambda q: bar.setText("" if q.toString() == "about:blank" else q.toString())); win.show(); sys.exit(app.exec())